version: '3.7'
services:
  slips:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: SlipsMy
    cap_add:
      - NET_ADMIN
    volumes:
      - ./slips/config:/StratosphereLinuxIPS/config/
      - ./logs/:/var/log/
    network_mode: "host"
    entrypoint: ["/bin/bash"]
  iris:
    build:
      context: C:/Users/timel/MyFolder/MOI_3/Stratosphere/Slips/iris
      dockerfile: Dockerfile
    container_name: IrisApp
    network_mode: "host"
