x-peer: &default-peer
  build:
    context: ./iris
    dockerfile: ./Dockerfile
  environment:
    - GOLOG_LOG_LEVEL=iris=debug
  command:
    - ./peercli
    - --conf
    - ./vol/config.yaml

services:
  slips:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: myslips
    cap_add:
      - NET_ADMIN
    volumes:
      - ./slips/config:/StratosphereLinuxIPS/config/
      - ./logs/:/var/log/
    network_mode: "host"

  iris:
    <<: *default-peer
    volumes:
      - ./iris/dev/peer:/usr/iris/vol
    depends_on:
      - slips
    network_mode: "host"
